# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.0

pipelines:
  default:
    - step:
        name: Building
        script:
          - npm install -g @angular/cli@1.7.4
          - npm install
          - ng build --base-href=/datatable/
          - cd dist/
          - git config --global user.email "sererejegede@gmail.com"
          - git config --global user.name "Serere Jegede"
          - git init
          - git add -A && git commit -m "base url updated for prod deployment"
          - git clone https://github.com/git-ftp/git-ftp.git
          - cd git-ftp
          - git checkout 1.3.4
          - make install
          - echo "Done with installation of git-ftp"
          - cd ../
          - rm -rf git-ftp
          - git config git-ftp.url "$ftphost$ftpsiteroot"
          - git config git-ftp.user $ftpusername
          - git config git-ftp.password $ftppassword
          - git ftp push --auto-init
          - echo "Finally done"
#    - step:
#        name: Deployment
#        script:
#          - apt-get update
#          - apt-get install ncftp
#          - ncftpput -v -u "$ftpusername" -p "$ftppassword" -R $ftphost $ftpsiteroot dist/*
#          - echo Finished uploading /dist files to $ftphost$ftpsiteroot

