# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.0

pipelines:
  default:
    - step:
        name: Installation
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
    - step:
        name: Building
        script:
          - npm install -g @angular/cli@1.7.4
          - npm install
          - ng build --base-href=/datatable/
    - step:
        name: Deployment
        script:
          - apt-get update
          - apt-get install ncftp
          - ncftpput -v -u "$ftpusername" -p "$ftppassword" -R $ftphost $ftpsiteroot dist/*
          - echo Finished uploading /dist files to $ftphost$ftpsiteroot
